### ISSUE TITLE
Is there foodName in these json files?

### ISSUE THREAD

**Issue by xenia19** [v3gtb/fooddata-vegattributes#144]
I wonder, if it's possible to add a column of food name.

**Comment by v3gtb** [comment]
I really didn't want to put names or any other non-category attributes in there as you can always get the full data for each entry by looking up the relevant IDs in the two USDA FoodData datasets, but I'll consider adding the names as they might be useful for cross-checking that the ID lookup works correctly.

**Comment by v3gtb** [comment]
@xenia19 I added a `description` field that just reproduces the description from the original USDA FDC data in the 1.1.0 release of the data set.
